Enhancement: This modification causes the schema compiler to fail early in case of a wrong NotionProperty format string. Before, the wrong format was silently accepted by the compiler but could lead to a NoClassDefFoundError (a Throwable which was ignored before) at runtime when a node object is instantiated for the first time. The node was then instantiated as GenericNode which lead to severe loss of functionality in the app layer.